### ISSUE TITLE
Markdown not updating

### ISSUE THREAD

**Issue by gsingh93** [evancz/elm-markdown#1]
I originally posted this on the elm-discuss mailing list and was told this was a bug, so I'm reporting it here.

This code works fine:

```
import Markdown
import Time (..)
import Signal (Signal, (<~))
import Graphics.Element (Element)
import Text (..)

main : Signal Element
main = display <~ (every second)

display : Time -> Element
display time = plainText <| toString time
```

But when I change the `plainText` to `Markdown.toElement` the time no longer updates:

```
import Markdown
import Time (..)
import Signal (Signal, (<~))
import Graphics.Element (Element)
import Text (..)

main : Signal Element
main = display <~ (every second)

display : Time -> Element
display time = Markdown.toElement <| toString time
```

I tested this locally but also on the editor on the Examples page. In the actual project where I ran into this issue, the text didn't change, but it looked like the width was changing.

**Comment by evancz** [comment]
It _appears_ that you can work around this for now by using something like this:

``` haskell
toElement w h txt =
    Html.toElement w h (Markdown.toHtml txt)
```

Though it's not exactly the same. Looking into underlying issue now.

**Comment by evancz** [comment]
I am planning to do a 0.14.1 release with a bunch of incremental fixes so this should be out relatively soon, maybe the next week or so.
