### ISSUE TITLE
Highlight.js is not working for html code blocks.

### ISSUE THREAD

**Issue by ryanucode** [evancz/elm-markdown#21]
Highlight.js is not working out of the box. I have created [a small SSCCE](https://github.com/ryanucode/elm-markdown-sscce) that demonstrates the issue.

In the [preview](https://ryanucode.github.io/elm-markdown-sscce/) I would expect to see the DOM modified by highlight.js. `window.hljs` is defined at the time I load the elm app as you can see in the javascript console.

**Comment by ryanucode** [comment]
I have refined this issue and the linked SSCCE a little bit. Highlight.js is not being called for html language block code.

In the [elm-markdown natice code](https://github.com/evancz/elm-markdown/blob/master/src/Native/Markdown.js#L83) you run a couple checks including calling `hljs.listLanguages()` to check if the language of the markdown code block is in the list. `html` is not, but xml is. I believe the HighlightJS initialization functions account for this translation while elm does not.

**Comment by kkruups** [comment]
## Fails to Highlight code

Highlight not working at all with or without defaultHighlight option being set for code compiled locally.

ran both:
  toHtml  (using defaults via online editor and locally, result works on Online Editor, fails on local system running elm-reactor)
  toHtmlWith  (configuring defaultHightlight only locally, fails)

Code highlighting works for Sample Code in Elm Online Editor, however the same code on local machine does not highlight code.

Link to Elm online Code:
http://elm-lang.org/examples/markdown

**Screenshot for Online Example:**
-------------------------------------------
![markdown_oe_output](https://cloud.githubusercontent.com/assets/1913254/22915118/5c11e2da-f2b8-11e6-998c-5da513269e44.png)


**Screen shot for locally compiled code:**

![markdown_no_highlight](https://cloud.githubusercontent.com/assets/1913254/22915130/6ddeb3c6-f2b8-11e6-8373-6a5810983b64.png)

**Comment by evancz** [comment]
Assuming that @kkruups example is the same as the original one, here's the answer: You need CSS to add the styles. If you examine the HTML structure locally, it's got extra tags and such if you have the highlight.js stuff working.
